// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJMf1echmyZ0qvy8BGff6JI0TFkGVvHs',
    appId: '1:392810018140:android:907202d4089cd789a6fd99',
    messagingSenderId: '392810018140',
    projectId: 'flutter-login-app-345b5',
    storageBucket: 'flutter-login-app-345b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9ED_HIdl0KGj2MpLBKXOo1ttdjHsuGw',
    appId: '1:392810018140:ios:a61d4747d375154ea6fd99',
    messagingSenderId: '392810018140',
    projectId: 'flutter-login-app-345b5',
    storageBucket: 'flutter-login-app-345b5.appspot.com',
    androidClientId: '392810018140-9qm4p7sldoo6fl4ij5vq9ut0emvcor0e.apps.googleusercontent.com',
    iosClientId: '392810018140-s2837tmn60l1mhq7id869bj7dtra9c0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
